<?php
declare(strict_types=1);

$dsn = 'mysql:host=localhost;dbname=chatbot;charset=utf8mb4';
$options = [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    PDO::ATTR_EMULATE_PREPARES => false,
];
$pdo = new PDO($dsn, 'chatbot', 'QeSjL&3P==9AkkSVfTA4', $options);
$pdo->exec("SET NAMES utf8mb4");

$questions = [
  "Hola, ¿cómo estás?",
  "¿Qué puedes hacer por mí?",
  "Cuéntame un chiste",
  "¿Cómo puedo mejorar mis habilidades sociales?",
  "Dame consejos para una primera cita",
  "¿Cómo superar la timidez?",
  "¿Qué opinas sobre las redes sociales?",
  "Ayúdame a escribir un mensaje de disculpa",
  "¿Cómo hacer nuevos amigos?",
  "Consejos para hablar en público",
  "¿Cómo lidiar con personas tóxicas?",
  "¿Qué significa ser empático?",
  "Dame tips para una entrevista de trabajo",
  "¿Cómo mantener una conversación interesante?",
  "¿Por qué es importante la escucha activa?",
  "¿Cómo manejar conflictos en una relación?",
  "Consejos para el trabajo en equipo",
  "¿Cómo ser más asertivo?",
  "¿Qué debo hacer si me siento solo?",
  "Tips para una buena comunicación con mi pareja",
  "¿Cómo reconocer a un verdadero amigo?",
  "¿Cuáles son las claves del liderazgo?",
  "Ayúdame a redactar una carta de amor",
  "¿Cómo superar una ruptura amorosa?",
  "¿Qué es la inteligencia emocional?",
  "Dame frases para iniciar una conversación",
  "¿Cómo actuar en una reunión social?",
  "Consejos para padres primerizos",
  "¿Cómo educar con amor y límites?",
  "¿Qué hacer cuando alguien te ignora?",
  "¿Cómo pedir ayuda sin sentir vergüenza?",
  "Tips para relacionarse mejor en el trabajo",
  "¿Cómo decir no sin ofender?",
  "¿Cómo recuperar la confianza de alguien?",
  "Consejos para una vida social saludable",
  "¿Qué es el gaslighting?",
  "¿Cómo identificar una relación codependiente?",
  "Dame ideas para romper el hielo en una fiesta",
  "¿Cómo apoyar a un amigo con depresión?",
  "¿Qué temas son seguros en una conversación?",
  "Consejos para escribir mejor en redes sociales",
  "¿Cómo manejar los celos?",
  "¿Qué hacer si me siento excluido?",
  "Tips para reconciliarse con un amigo",
  "¿Cómo expresar gratitud genuinamente?",
  "¿Qué es el amor propio y cómo cultivarlo?",
  "Consejos para una boda memorable",
  "¿Cómo presentar a mi pareja a mi familia?",
  "¿Qué debo evitar en una primera impresión?",
  "Dame ejemplos de cumplidos sinceros",
  "¿Cómo lidiar con la presión social?",
  "¿Cómo ser un buen oyente?",
  "Tips para una conversación por video llamada",
  "¿Cómo mantener amistades a distancia?",
  "¿Qué regalarle a alguien que no conozco bien?",
  "Consejos para una cena de negocios",
  "¿Cómo responder a un cumplido?",
  "¿Cómo iniciar una amistad en el gimnasio?",
  "¿Qué hacer si un amigo me debe dinero?",
  "Dame ideas de actividades en grupo",
  "¿Cómo superar el miedo al rechazo?",
  "Tips para ser más carismático",
  "¿Cómo manejar chismes en el trabajo?",
  "¿Qué significa tener boundaries sanos?",
  "Consejos para una despedida de soltero",
  "¿Cómo hablar con mi jefe sobre un problema?",
  "¿Cómo animar a un amigo triste?",
  "¿Qué temas evitar en una cita?",
  "Dame frases para terminar una conversación educadamente",
  "¿Cómo reconectar con viejos amigos?",
  "Tips para una llamada telefónica profesional",
  "¿Cómo pedir una cita sin nervios?",
  "¿Qué hacer si me siento invisible en mi grupo?",
  "Consejos para una reunión familiar tensa",
  "¿Cómo apoyar a alguien que perdió a un ser querido?",
  "¿Cómo aceptar críticas constructivas?",
  "Dame ideas para romper el hielo en el trabajo",
  "¿Cómo saber si alguien es falso?",
  "Tips para ser más paciente con los demás",
  "¿Cómo celebrar un cumpleaños inolvidable?",
  "¿Qué hacer si mi pareja y yo discutimos mucho?",
  "Consejos para una conversación difícil",
  "¿Cómo mostrar interés genuino en alguien?",
  "¿Cómo manejar la envidia?",
  "Dame ejemplos de mensajes de buenos días",
  "¿Cómo ser más sociable si soy introvertido?",
  "Tips para una cita virtual exitosa",
  "¿Cómo reaccionar ante una broma incómoda?",
  "¿Qué hacer si alguien me interrumpe siempre?",
  "Consejos para una despedida de trabajo",
  "¿Cómo escribir un mensaje de condolencias?",
  "¿Cómo superar el miedo a las multitudes?",
  "Dame frases para motivar a un amigo",
  "¿Cómo actuar cuando no conoces a nadie en una fiesta?",
  "Tips para hablar con niños",
  "¿Cómo saber si estoy en una relación tóxica?",
  "¿Qué hacer si mi mejor amigo me decepcionó?",
  "Consejos para una propuesta de matrimonio",
  "¿Cómo mantener el contacto con excompañeros?",
  "¿Cómo agradecer un regalo de forma especial?",
  "Dame ideas para una cita creativa",
  "¿Cómo lidiar con la soledad emocional?",
  "Tips para ser más abierto con los demás",
  "¿Cómo perdonar a alguien que me lastimó?",
  "¿Qué hacer si siento que no encajo?",
  "Consejos para una fiesta sorpresa",
  "¿Cómo expresar mis emociones sin ofender?",
  "¿Cómo mejorar mi lenguaje corporal?",
  "Dame ejemplos de mensajes de ánimo",
  "¿Cómo actuar ante una traición?",
  "Tips para una conversación con mi ex",
  "¿Cómo construir confianza en una relación nueva?",
  "¿Qué hacer si alguien me hace ghosting?",
  "Consejos para una reunión de padres de familia",
  "¿Cómo ser más auténtico socialmente?",
  "¿Cómo manejar el estrés social?",
  "Dame frases para iniciar una amistad",
  "¿Cómo ayudar a alguien con ansiedad social?",
  "Tips para una llamada de cumpleaños",
  "¿Cómo reconocer señales de alerta en una amistad?",
  "¿Qué hacer si me siento presionado por mi círculo social?",
  "Consejos para una cena romántica en casa",
  "¿Cómo hablar sobre dinero con mi pareja?",
  "¿Cómo superar el miedo a hablar por teléfono?",
  "Dame ideas para fortalecer lazos familiares",
  "¿Cómo ser más considerado con los demás?",
  "Tips para una videollamada de trabajo",
  "¿Cómo manejar un amigo muy negativo?",
  "¿Qué hacer si alguien copia mi personalidad?",
  "Consejos para una despedida de año",
  "¿Cómo expresar preocupación sin ser invasivo?",
  "¿Cómo iniciar una conversación profunda?",
  "Dame ejemplos de mensajes de despedida",
  "¿Cómo actuar cuando alguien está llorando?",
  "Tips para una reunión de vecinos",
  "¿Cómo superar el miedo a conocer gente nueva?",
  "¿Qué hacer si mi pareja no me escucha?",
  "Consejos para una cita de aniversario",
  "¿Cómo pedir un favor sin molestar?",
  "¿Cómo mantener la calma en una discusión?",
  "Dame frases para felicitar a alguien",
  "¿Cómo lidiar con la comparación social?",
  "Tips para ser más accesible",
  "¿Cómo reconectar con un hermano distante?",
  "¿Qué hacer si me siento juzgado?",
  "Consejos para una conversación sobre salud mental",
  "¿Cómo ser más positivo en interacciones sociales?",
  "¿Cómo responder a comentarios pasivo-agresivos?",
  "Dame ideas para una tarde de amigos",
  "¿Cómo manejar la ansiedad antes de una fiesta?",
  "Tips para una entrevista de amistad",
  "¿Cómo saber si una amistad es genuina?",
  "¿Qué hacer si alguien monopoliza la conversación?",
  "Consejos para una despedida de viaje",
  "¿Cómo hablar con mi pareja sobre metas futuras?",
  "¿Cómo superar el miedo al compromiso social?",
  "Dame ejemplos de mensajes de buenas noches",
  "¿Cómo actuar ante un cumplido inesperado?",
  "Tips para una videollamada con la familia",
  "¿Cómo manejar el silencio incómodo?",
  "¿Qué hacer si un amigo me envidia?",
  "Consejos para una reunión de trabajo informal",
  "¿Cómo pedir espacio sin herir sentimientos?",
  "¿Cómo mejorar mi empatía?",
  "Dame frases para animar a un compañero",
  "¿Cómo superar una pelea con un amigo?",
  "Tips para una cita de día",
  "¿Cómo establecer límites con mi familia?",
  "¿Qué hacer si siento que mi pareja se distancia?",
  "Consejos para una cena con suegros",
  "¿Cómo ser más interesante en conversaciones?",
  "¿Cómo responder cuando alguien me insulta?",
  "Dame ideas para celebrar una amistad",
  "¿Cómo manejar el estrés en eventos sociales?",
  "Tips para una conversación con mi mentor",
  "¿Cómo saber si estoy siendo manipulado?",
  "¿Qué hacer si mi grupo de amigos cambió?",
  "Consejos para una despedida de universidad",
  "¿Cómo expresar enojo de forma saludable?",
  "¿Cómo iniciar una amistad en línea?",
  "Dame ejemplos de mensajes de apoyo",
  "¿Cómo actuar cuando alguien me ignora en redes?",
  "Tips para una reunión de antiguos compañeros",
  "¿Cómo superar el miedo a la intimidad emocional?",
  "¿Qué hacer si mi amigo tiene una adicción?",
  "Consejos para una cita de San Valentín",
  "¿Cómo pedir disculpas de corazón?",
  "¿Cómo mantener viva una conversación por chat?",
  "Dame frases para reconfortar a alguien",
  "¿Cómo lidiar con la culpa social?",
  "Tips para ser más sociable en el trabajo",
  "¿Cómo reconocer una amistad superficial?",
  "¿Qué hacer si me siento abandonado por amigos?",
  "Consejos para una fiesta de cumpleaños",
  "¿Cómo hablar sobre temas delicados?",
  "¿Cómo superar el miedo a exponerme?",
  "Dame ideas para una cita en casa",
  "¿Cómo manejar comentarios sobre mi vida personal?",
  "Tips para una llamada con un cliente",
  "¿Cómo saber si mi pareja me respeta?",
  "¿Qué hacer si alguien me hace sentir inferior?",
  "Consejos para una reunión de vecindario",
  "¿Cómo ser más asertivo con extraños?",
  "¿Cómo responder a un mensaje ofensivo?",
  "Dame ejemplos de mensajes de amistad",
  "¿Cómo superar el miedo a pedir ayuda?",
  "Tips para una videollamada romántica",
  "¿Cómo manejar una ruptura de amistad?",
  "¿Qué hacer si mi familia no acepta mi pareja?",
  "Consejos para una despedida de soltera",
  "¿Cómo mostrar vulnerabilidad sin miedo?",
  "¿Cómo iniciar una conversación con un vecino?",
  "Dame frases para agradecer a un amigo",
  "¿Cómo lidiar con la presión de tener pareja?",
  "Tips para una entrevista de podcast",
  "¿Cómo saber si alguien me quiere cerca?",
  "¿Qué hacer si me siento excluido de conversaciones?",
  "Consejos para una cita de picnic",
  "¿Cómo hablar con mi hijo adolescente?",
  "¿Cómo superar el miedo a ser juzgado?",
  "Dame ideas para una noche de juegos",
  "¿Cómo manejar la ansiedad en reuniones familiares?",
  "Tips para ser más divertido socialmente",
  "¿Cómo reconocer el apoyo emocional genuino?",
  "¿Qué hacer si un amigo me traicionó?",
  "Consejos para una fiesta de inauguración",
  "¿Cómo expresar mis necesidades emocionales?",
  "¿Cómo actuar cuando alguien está enojado conmigo?",
  "Dame ejemplos de mensajes de ánimo laboral",
  "¿Cómo superar el miedo a las presentaciones?",
  "Tips para una cita a ciegas",
  "¿Cómo establecer rutinas de conexión con mi pareja?",
  "¿Qué hacer si mi jefe me intimida?",
  "Consejos para una despedida de militar",
  "¿Cómo ser más amable sin ser sumiso?",
  "¿Cómo responder a un chisme sobre mí?",
  "Dame frases para motivar a mi equipo",
  "¿Cómo lidiar con el fracaso social?",
  "Tips para una conversación de retroalimentación",
  "¿Cómo saber si debo terminar una amistad?",
  "¿Qué hacer si alguien me copia en redes?",
  "Consejos para una reunión de trabajo remoto",
  "¿Cómo pedir tiempo para mí sin culpa?",
  "¿Cómo mejorar mi presencia en redes sociales?",
  "Dame ideas para una cita cultural",
  "¿Cómo manejar la frustración con amigos?",
  "Tips para una llamada de condolencias",
  "¿Cómo superar el miedo a la confrontación?",
  "¿Qué hacer si siento que mi pareja no me valora?",
  "Consejos para una cita en la playa",
  "¿Cómo hablar de mis logros sin sonar presumido?",
  "¿Cómo actuar en una cena formal?",
  "Dame ejemplos de mensajes de despedida de soltero",
  "¿Cómo lidiar con la nostalgia de amigos lejanos?",
  "Tips para ser más sociable en clase",
  "¿Cómo reconocer cuando necesito espacio?",
  "¿Qué hacer si mi compañero de trabajo me evita?",
  "Consejos para una reunión de equipo nuevo",
  "¿Cómo expresar tristeza sin cargar a otros?",
  "¿Cómo iniciar una conversación en el ascensor?",
  "Dame frases para celebrar logros de amigos",
  "¿Cómo manejar el rechazo amoroso?",
  "Tips para una videollamada de estudio",
  "¿Cómo saber si mi pareja es compatible conmigo?",
  "¿Qué hacer si mi familia compara con mis hermanos?",
  "Consejos para una fiesta de Halloween",
  "¿Cómo pedir claridad sin sonar exigente?",
  "¿Cómo superar el miedo a la vulnerabilidad?",
  "Dame ideas para una cita deportiva",
  "¿Cómo actuar ante un cumplido falso?",
  "Tips para una conversación con mi terapeuta",
  "¿Cómo manejar la competencia entre amigos?",
  "¿Qué hacer si siento que mi mejor amigo cambió?",
  "Consejos para una despedida de intercambio",
  "¿Cómo ser más paciente con mi familia?",
  "¿Cómo responder cuando alguien me critica en público?",
  "Dame ejemplos de mensajes de bienvenida",
  "¿Cómo superar la inseguridad social?",
  "Tips para una cita en museo",
  "¿Cómo establecer confianza con nuevos compañeros?",
  "¿Qué hacer si alguien me hace sentir culpable?",
  "Consejos para una reunión de proyecto escolar",
  "¿Cómo hablar sobre mis límites personales?",
  "¿Cómo mantener el entusiasmo en relaciones largas?",
  "Dame frases para reconocer el esfuerzo de alguien",
  "¿Cómo lidiar con la distancia emocional?",
  "Tips para ser más natural en videollamadas",
  "¿Cómo reconocer una buena comunicación de pareja?",
  "¿Qué hacer si mi familia no respeta mis decisiones?",
  "Consejos para una despedida de temporada",
  "¿Cómo pedir tiempo a solas en una relación?",
  "¿Cómo superar el miedo a la apertura emocional?",
  "Dame ejemplos de mensajes de agradecimiento a un mentor",
  "¿Cómo lidiar con un amigo que todo lo sabe?",
  "Tips para una cita de feria local",
  "¿Cómo saber si mi pareja es narcisista?",
  "¿Qué hacer si alguien me hace sentir responsable de su felicidad?",
  "Consejos para una reunión de vecinos nuevos",
  "¿Cómo expresar desacuerdo sin romper una amistad?",
  "¿Cómo actuar cuando alguien está nervioso a mi lado?",
  "Dame frases para celebrar un nuevo trabajo",
  "¿Cómo manejar la presión de tener hijos?",
  "Tips para una conversación de cierre de proyecto",
  "¿Cómo reconocer el amor propio en acción?",
  "¿Qué hacer si mi amigo me critica constantemente?",
  "Consejos para una fiesta de inauguración de casa",
  "¿Cómo ser más considerado con personas mayores?",
  "¿Cómo responder cuando alguien me dice te quiero?",
  "Dame ideas para una cita de voluntariado",
  "¿Cómo lidiar con el abandono en una relación?",
  "Tips para ser más extrovertido gradualmente",
  "¿Cómo saber si mi pareja y yo somos compatibles a largo plazo?",
  "¿Qué hacer si mi grupo de amigos me excluye?",
  "Consejos para una reunión de trabajo presencial",
  "¿Cómo pedir espacio emocional de forma clara?",
  "¿Cómo superar el miedo a ser vulnerable con amigos?",
  "Dame ejemplos de mensajes de aliento para deportistas",
  "¿Cómo actuar en una cita de lujo?",
  "Tips para una videollamada de aniversario",
  "¿Cómo manejar el cambio de dinámica en una amistad?",
  "¿Qué hacer si mi pareja me da la espalda emocionalmente?",
  "Consejos para una fiesta sorpresa de cumpleaños",
  "¿Cómo expresar creatividad en regalos?",
  "¿Cómo actuar cuando alguien me da las gracias?",
  "Dame frases para reconfortar a un estudiante estresado",
  "¿Cómo lidiar con la frustración en relaciones?",
  "Tips para una cita de mini golf",
  "¿Cómo reconocer el apoyo de mi comunidad?",
  "¿Qué hacer si mi familia no entiende mi carrera?",
  "Consejos para una despedida de estudios",
  "¿Cómo pedir comprensión sin sonar dramático?",
  "¿Cómo mantener la amistad después de una discusión política?",
  "Dame ideas para una cita de mercado de pulgas",
  "¿Cómo manejar la ansiedad en eventos familiares?",
  "Tips para ser más comprensivo con mi pareja",
  "¿Cómo saber si alguien está interesado en mí?",
  "¿Qué hacer si mi amigo me cuenta un secreto pesado?",
  "Consejos para una reunión de condominio",
  "¿Cómo expresar orgullo profesional sin arrogancia?",
  "¿Cómo actuar en una cita de desayuno?",
  "Dame ejemplos de mensajes de ánimo para artistas",
  "¿Cómo superar el miedo a la crítica social?",
  "Tips para una conversación sobre salud con mi pareja",
  "¿Cómo reconocer cuando una amistad evolucionó?",
  "¿Qué hacer si mi jefe me pide favores personales?",
  "Consejos para una fiesta de Halloween en casa",
  "¿Cómo ser más auténtico en citas?",
  "¿Cómo responder cuando alguien me pide perdón?",
  "Dame frases para celebrar una graduación",
  "¿Cómo lidiar con la presión de ser perfecto?",
  "Tips para una cita de escape room",
  "¿Cómo saber si mi pareja valora mi tiempo?",
  "¿Qué hacer si mi amigo está en una relación tóxica?",
  "Consejos para una reunión de planificación familiar",
  "¿Cómo pedir apoyo sin sentirme débil?",
  "¿Cómo mantener el romance en una relación madura?",
  "Dame ideas para una cita de naturaleza",
  "¿Cómo manejar comentarios sobre mi soltería?",
  "Tips para ser más asertivo con mi familia",
  "¿Cómo reconocer una conversación manipuladora?",
  "¿Qué hacer si mi pareja me evita?",
  "Consejos para una despedida de escuela",
  "¿Cómo expresar cariño de formas no verbales?",
  "¿Cómo actuar cuando alguien está celebrando?",
  "Dame ejemplos de mensajes de solidaridad",
  "¿Cómo superar el miedo a la interdependencia?",
  "Tips para una videollamada de juegos",
  "¿Cómo manejar una ruptura amistosa profesional?",
  "¿Qué hacer si mi familia tiene expectativas irreales?",
  "Consejos para una fiesta de verano",
  "¿Cómo ser más empático con extraños?",
  "¿Cómo responder a un cumplido sobre mi carácter?",
  "Dame frases para reconfortar a un padre primerizo",
  "¿Cómo lidiar con el sentimiento de no pertenecer?",
  "Tips para una cita de zoológico",
  "¿Cómo saber si mi pareja está comprometida?",
  "¿Qué hacer si mi amigo me hace sentir culpable por mis éxitos?",
  "Consejos para una reunión de amigos de la infancia",
  "¿Cómo pedir una cita formalmente?",
  "¿Cómo superar el miedo a la exposición emocional?",
  "Dame ideas para una tarde de manualidades",
  "¿Cómo manejar la distancia geográfica en amistades?",
  "Tips para ser más sociable en una conferencia",
  "¿Cómo reconocer el agradecimiento genuino?",
  "¿Qué hacer si mi pareja no responde mis mensajes?",
  "Consejos para una cita de acuario",
  "¿Cómo expresar mis logros personales?",
  "¿Cómo actuar cuando alguien está de luto?",
  "Dame ejemplos de mensajes de apoyo para madres solteras",
  "¿Cómo lidiar con la ansiedad de presentar a alguien?",
  "Tips para una conversación de desarrollo personal",
  "¿Cómo saber si mi amistad es saludable?",
  "¿Qué hacer si mi jefe me invita a salir?",
  "Consejos para una fiesta de graduación universitaria",
  "¿Cómo mantener la individualidad en una relación?",
  "¿Cómo responder a un mensaje de reconciliación?",
  "Dame frases para celebrar la diversidad",
  "¿Cómo manejar la culpa de decir no a un plan?",
  "Tips para una cita de realidad virtual",
  "¿Cómo reconocer cuando alguien proyecta sus inseguridades?",
  "¿Qué hacer si mi grupo de amigos crea drama?",
  "Consejos para una reunión de trabajo de fin de año",
  "¿Cómo pedir ayuda en una crisis personal?",
  "¿Cómo superar el miedo a la aprobación social?",
  "Dame ideas para una cita de observación de aves",
  "¿Cómo actuar en una fiesta de oficina virtual?",
  "Tips para ser más considerado con compañeros nuevos",
  "¿Cómo saber si mi pareja es emocionalmente disponible?",
  "¿Qué hacer si mi amigo me envidia profesionalmente?",
  "Consejos para una despedida de compañeros de trabajo",
  "¿Cómo expresar tristeza sin ser juzgado?",
  "¿Cómo mantener la amistad a pesar de diferencias ideológicas?",
  "Dame ejemplos de mensajes de apoyo para padres adoptivos",
  "¿Cómo lidiar con la sensación de estar estancado socialmente?",
  "Tips para una cita de festival de música",
  "¿Cómo reconocer el valor de mis amistades?",
  "¿Qué hacer si mi familia me presiona económicamente?",
  "Consejos para una fiesta de bienvenida",
  "¿Cómo ser más proactivo en mis relaciones?",
  "¿Cómo responder cuando alguien comparte buenas noticias?",
  "Dame frases para motivar a alguien en rehab",
  "¿Cómo manejar la decepción en una relación?",
  "Tips para una conversación sobre cambio de carrera",
  "¿Cómo saber si debo confiar en alguien nuevo?",
  "¿Qué hacer si mi pareja me compara con su ex?",
  "Consejos para una reunión de amigos de viaje",
  "¿Cómo pedir un favor delicado?",
  "¿Cómo superar el miedo a la desconexión emocional?",
  "Dame ideas para una cita de bodega",
  "¿Cómo actuar cuando alguien está celoso de mí?",
  "Tips para ser más agradecido socialmente",
  "¿Cómo reconocer la manipulación emocional?",
  "¿Qué hacer si mi amigo no acepta mis disculpas?",
  "Consejos para una fiesta de compromiso informal",
  "¿Cómo expresar alegría compartida?",
  "¿Cómo mantener la paz en una familia numerosa?",
  "Dame ejemplos de mensajes de esperanza",
  "¿Cómo lidiar con el rechazo de un grupo?",
  "Tips para una cita de feria gastronómica",
  "¿Cómo saber si mi pareja valora mi opinión?",
  "¿Qué hacer si mi jefe me ignora en reuniones?",
  "Consejos para una despedida de club deportivo",
  "¿Cómo ser más paciente con personas difíciles?",
  "¿Cómo responder a un comentario sobre mi vida amorosa?",
  "Dame frases para reconfortar a alguien con burnout",
  "¿Cómo manejar la envidia hacia mi pareja?",
  "Tips para una videollamada de amigos internacionales",
  "¿Cómo reconocer una conversación constructiva?",
  "¿Qué hacer si mi familia minimiza mis logros?",
  "Consejos para una reunión de trabajo creativo",
  "¿Cómo pedir explicaciones sin sonar acusador?",
  "¿Cómo superar el miedo a ser olvidado?",
  "Dame ideas para una cita de observación de ballenas",
  "¿Cómo actuar cuando alguien admite un error?",
  "Tips para ser más transparente en mis relaciones",
  "¿Cómo saber si mi amistad está basada en intereses?",
  "¿Qué hacer si mi pareja me miente sobre pequeñeces?",
  "Consejos para una fiesta de Halloween para niños",
  "¿Cómo expresar necesidad de cercanía?",
  "¿Cómo mantener el contacto con excompañeros de trabajo?",
  "Dame ejemplos de mensajes de felicitación por un bebé",
  "¿Cómo lidiar con la frustración de no ser escuchado?",
  "Tips para una cita de teatro",
  "¿Cómo reconocer una buena dinámica de equipo?",
  "¿Qué hacer si mi amigo me deja de hablar de repente?",
  "Consejos para una despedida de campo",
  "¿Cómo ser más flexible socialmente?",
  "¿Cómo responder cuando alguien me pide un consejo?",
  "Dame frases para celebrar la superación personal",
  "¿Cómo manejar la presión de tener una vida social activa?",
  "Tips para una conversación de resolución de conflictos",
  "¿Cómo saber si mi pareja me respeta emocionalmente?",
  "¿Qué hacer si mi familia no acepta mi orientación?",
  "Consejos para una fiesta de pool party",
  "¿Cómo pedir perdón a mi pareja?",
  "¿Cómo superar el miedo a la soledad?",
  "Dame ideas para una cita de museo de ciencias",
  "¿Cómo actuar cuando alguien está intoxicado en una fiesta?",
  "Tips para ser más respetuoso en debates",
  "¿Cómo reconocer la lealtad en una amistad?",
  "¿Qué hacer si mi jefe me culpa por errores ajenos?",
  "Consejos para una reunión de trabajo de emergencia",
  "¿Cómo expresar entusiasmo por un proyecto compartido?",
  "¿Cómo mantener amistades durante una pandemia?",
  "Dame ejemplos de mensajes de aliento para estudiantes",
  "¿Cómo lidiar con la culpa de no estar disponible?",
  "Tips para una cita de jardín botánico",
  "¿Cómo saber si mi pareja valora mi crecimiento?",
  "¿Qué hacer si mi amigo me pide dinero constantemente?",
  "Consejos para una despedida de coro",
  "¿Cómo ser más tolerante con diferencias culturales?",
  "¿Cómo responder a un mensaje de despedida de un amigo?",
  "Dame frases para reconfortar a alguien con ansiedad",
  "¿Cómo manejar el estrés de las reuniones familiares grandes?",
  "Tips para una conversación sobre mudanza con mi pareja",
  "¿Cómo reconocer una relación de apoyo mutuo?",
  "¿Qué hacer si mi familia me compara con otros?",
  "Consejos para una fiesta de inauguración de negocio",
  "¿Cómo pedir un aumento sin dañar la relación?",
  "¿Cómo superar el miedo a la crítica constructiva?",
  "Dame ideas para una cita de paseo en bicicleta",
  "¿Cómo actuar cuando alguien está pasando por un divorcio?",
  "Tips para ser más solidario con mis vecinos",
  "¿Cómo saber si mi amistad es incondicional?",
  "¿Qué hacer si mi pareja no quiere compromisos a largo plazo?",
  "Consejos para una reunión de trabajo híbrido",
  "¿Cómo expresar admiración por un colega?",
  "¿Cómo mantener la armonía en un grupo de roommates?",
  "Dame ejemplos de mensajes de aliento para emprendedores",
  "¿Cómo lidiar con la ansiedad de una primera cita?",
  "Tips para una cita de feria del libro",
  "¿Cómo reconocer cuando una relación necesita pausa?",
  "¿Qué hacer si mi amigo me cuenta una infidelidad?",
  "Consejos para una fiesta de aniversario de bodas",
  "¿Cómo ser más receptivo a feedback?",
  "¿Cómo responder cuando alguien me invita a algo que no quiero?",
  "Dame frases para celebrar un logro deportivo",
  "¿Cómo manejar la distancia emocional con mi familia?",
  "Tips para una conversación sobre vacaciones con amigos",
  "¿Cómo saber si mi pareja me apoya en mis metas?",
  "¿Qué hacer si mi jefe es pasivo-agresivo?",
  "Consejos para una despedida de club de fotografía",
  "¿Cómo pedir ayuda sin sentir que molesto?",
  "¿Cómo superar el miedo a la apertura con desconocidos?",
  "Dame ideas para una cita de parque acuático",
  "¿Cómo actuar cuando alguien está teniendo una crisis?",
  "Tips para ser más atento en conversaciones grupales",
  "¿Cómo reconocer el respeto en una relación?",
  "¿Qué hacer si mi familia no respeta mi privacidad?",
  "Consejos para una reunión de trabajo de planeación estratégica",
  "¿Cómo expresar cariño a distancia?",
  "¿Cómo mantener el interés en conversaciones largas?",
  "Dame ejemplos de mensajes de apoyo para personas mayores",
  "¿Cómo lidiar con la inseguridad de mi pareja?",
  "Tips para una cita de tienda de antigüedades",
  "¿Cómo saber si mi amistad es genuinamente recíproca?",
  "¿Qué hacer si mi amigo me hace bromas que duelen?",
  "Consejos para una fiesta de cumpleaños sorpresa",
  "¿Cómo ser más abierto a nuevas amistades?",
  "¿Cómo responder cuando alguien me dice que cambié?",
  "Dame frases para reconfortar a alguien con problemas legales",
  "¿Cómo manejar la presión de mi círculo para tomar decisiones?",
  "Tips para una videollamada de trabajo internacional",
  "¿Cómo reconocer una conversación tóxica?",
  "¿Qué hacer si mi pareja no me incluye en sus planes?",
  "Consejos para una despedida de grupo de estudio",
  "¿Cómo pedir claridad en una relación confusa?",
  "¿Cómo superar el miedo a la dependencia emocional?",
  "Dame ideas para una cita de cine al aire libre",
  "¿Cómo actuar cuando alguien me hace un regalo inesperado?",
  "Tips para ser más paciente con mi pareja",
  "¿Cómo saber si mi jefe valora mi trabajo?",
  "¿Qué hacer si mi familia me hace sentir inadecuado?",
  "Consejos para una fiesta de Halloween de adultos",
  "¿Cómo expresar orgullo por un familiar?",
  "¿Cómo mantener la amistad después de mudarse?",
  "Dame ejemplos de mensajes de aliento para artistas",
  "¿Cómo lidiar con el aislamiento social?",
  "Tips para una cita de paseo en barco",
  "¿Cómo reconocer señales de agotamiento emocional en amigos?",
  "¿Qué hacer si mi pareja me da ultimátums?",
  "Consejos para una reunión de trabajo de retroalimentación 360",
  "¿Cómo ser más constante en mantener contacto?",
  "¿Cómo responder cuando alguien me dice que soy especial?",
  "Dame frases para celebrar una nueva etapa de vida",
  "¿Cómo manejar la culpa de priorizar mi bienestar?",
  "Tips para una conversación sobre maternidad con mi pareja",
  "¿Cómo saber si mi amistad me está limitando?",
  "¿Qué hacer si mi jefe me pide que trabaje gratis?",
  "Consejos para una fiesta de despedida de soltero",
  "¿Cómo pedir que me traten con respeto?",
  "¿Cómo superar el miedo a la soledad en la vejez?",
  "Dame ideas para una cita de mercado de agricultores",
  "¿Cómo actuar cuando alguien está deprimido a mi alrededor?",
  "Tips para ser más empático en el trabajo",
  "¿Cómo reconocer una buena química en una cita?",
  "¿Qué hacer si mi familia me culpa por todo?",
  "Consejos para una despedida de trabajo remoto",
  "¿Cómo expresar gratitud por pequeños gestos?",
  "¿Cómo mantener la amistad con ex compañeros de clase?",
  "Dame ejemplos de mensajes de apoyo para personas con discapacidad",
  "¿Cómo lidiar con la presión de encontrar pareja?",
  "Tips para una cita de museo de arte moderno",
  "¿Cómo saber si mi pareja está interesada en mejorar la relación?",
  "¿Qué hacer si mi amigo me ignora por su nueva pareja?",
  "Consejos para una reunión de trabajo de onboarding",
  "¿Cómo ser más proactivo en expresar afecto?",
  "¿Cómo responder cuando alguien me dice que inspire confianza?",
  "Dame frases para reconfortar a alguien con problemas financieros",
  "¿Cómo manejar la decepción de un ser querido?",
  "Tips para una videollamada de trabajo con cliente",
  "¿Cómo reconocer cuando una relación es asimétrica?",
  "¿Qué hacer si mi jefe me intimida verbalmente?",
  "Consejos para una fiesta de cumpleaños temática",
  "¿Cómo pedir tiempo para pensar en una relación?",
  "¿Cómo superar el miedo a la apertura total?",
  "Dame ideas para una cita de paseo nocturno",
  "¿Cómo actuar cuando alguien celebra mi fracaso?",
  "Tips para ser más comprensivo con mis padres",
  "¿Cómo saber si mi amistad superó una prueba difícil?",
  "¿Qué hacer si mi pareja no me defiende frente a otros?",
  "Consejos para una despedida de voluntarios",
  "¿Cómo expresar preocupación por un amigo sin invadir?",
  "¿Cómo mantener la privacidad de pareja en redes sociales?",
  "Dame ejemplos de mensajes de aliento para estudiantes de medicina",
  "¿Cómo lidiar con la ansiedad de una entrevista social?",
  "Tips para una cita de observación de ballenas",
  "¿Cómo reconocer el esfuerzo de mi pareja?",
  "¿Qué hacer si mi familia no respeta mi tiempo?",
  "Consejos para una reunión de trabajo de brainstorming",
  "¿Cómo ser más sensible a las necesidades ajenas?",
  "¿Cómo responder cuando alguien me dice que lo siente?",
  "Dame frases para celebrar un aniversario de trabajo",
  "¿Cómo manejar la presión de tener una imagen perfecta?",
  "Tips para una conversación sobre adopción con mi pareja",
  "¿Cómo saber si mi amistad necesita un break?",
  "¿Qué hacer si mi amigo me manipula emocionalmente?",
  "Consejos para una fiesta de inauguración de tienda",
  "¿Cómo pedir comprensión por mis límites sociales?",
  "¿Cómo superar el miedo a la exposición pública?",
  "Dame ideas para una cita de cata de vinos",
  "¿Cómo actuar cuando alguien está teniendo un ataque de pánico?",
  "Tips para ser más natural en redes sociales",
  "¿Cómo reconocer una relación emocionalmente segura?",
  "¿Qué hacer si mi pareja no quiere ir a terapia?",
  "Consejos para una despedida de campamento",
  "¿Cómo expresar admiración por un amigo?",
  "¿Cómo mantener el contacto con amigos del extranjero?",
  "Dame ejemplos de mensajes de apoyo para personas en recuperación",
  "¿Cómo lidiar con la envidia hacia mis amigos?",
  "Tips para una cita de paseo por la ciudad",
  "¿Cómo saber si mi pareja valora mi honestidad?",
  "¿Qué hacer si mi jefe me pide secretos personales?",
  "Consejos para una reunión de trabajo de seguimiento",
  "¿Cómo ser más considerado con personas con ansiedad?",
  "¿Cómo responder cuando alguien me pide espacio?",
  "Dame frases para reconfortar a alguien con dolor crónico",
  "¿Cómo manejar la presión de una relación seria?",
  "Tips para una videollamada de trabajo matutina",
  "¿Cómo reconocer una conversación empática?",
  "¿Qué hacer si mi familia no entiende mi salud mental?",
  "Consejos para una fiesta de Halloween familiar",
  "¿Cómo pedir ayuda para superar una adicción?",
  "¿Cómo superar el miedo a la soledad permanente?",
  "Dame ideas para una cita de juegos de mesa",
  "¿Cómo actuar cuando alguien está teniendo una crisis existencial?",
  "Tips para ser más abierto a recibir amor",
  "¿Cómo saber si mi amistad es auténtica?",
  "¿Qué hacer si mi pareja me hace sentir inseguro?",
  "Consejos para una despedida de coro juvenil",
  "¿Cómo expresar afecto sin palabras?",
  "¿Cómo mantener la amistad después de una diferencia religiosa?",
  "Dame ejemplos de mensajes de aliento para personas sin hogar",
  "¿Cómo lidiar con la presión de tener una familia perfecta?",
  "Tips para una cita de observación de estrellas fugaces",
  "¿Cómo reconocer cuando una relación me hace crecer?",
  "¿Qué hacer si mi amigo me cuenta que está enfermo terminal?",
  "Consejos para una reunión de trabajo de cierre de mes",
  "¿Cómo ser más respetuoso con los espacios ajenos?",
  "¿Cómo responder cuando alguien me dice que lo valoro?",
  "Dame frases para celebrar la resiliencia",
  "¿Cómo manejar el estrés de mantener muchas amistades?",
  "Tips para una conversación sobre jubilación con mi pareja",
  "¿Cómo saber si mi pareja es mi mejor amigo?",
  "¿Qué hacer si mi familia me presiona a estudiar algo que no quiero?",
  "Consejos para una fiesta de Halloween de mascotas",
  "¿Cómo pedir que me incluyan en planes?",
  "¿Cómo superar el miedo a ser juzgado por mis emociones?",
  "Dame ideas para una cita de picnic nocturno",
  "¿Cómo actuar cuando alguien está teniendo un momento de vergüenza?",
  "Tips para ser más empático con animales",
  "¿Cómo reconocer una relación basada en el respeto?",
  "¿Qué hacer si mi jefe me discrimina?",
  "Consejos para una despedida de club de debate",
  "¿Cómo expresar entusiasmo por un nuevo proyecto?",
  "¿Cómo mantener la paz en una reunión familiar conflictiva?",
  "Dame ejemplos de mensajes de apoyo para inmigrantes",
  "¿Cómo lidiar con la ansiedad de una reunión de trabajo?",
  "Tips para una cita de tienda de discos",
  "¿Cómo saber si mi amistad tiene futuro?",
  "¿Qué hacer si mi pareja no respeta mis amistades?",
  "Consejos para una fiesta de Halloween de disfraces",
  "¿Cómo ser más generoso con mi tiempo social?",
  "¿Cómo responder cuando alguien me dice que necesita ayuda?",
  "Dame frases para reconfortar a alguien con problemas de pareja",
  "¿Cómo manejar la culpa de no poder ayudar a todos?",
  "Tips para una videollamada de trabajo vespertina",
  "¿Cómo reconocer una conversación en la que me siento seguro?",
  "¿Qué hacer si mi familia me ignora en reuniones?",
  "Consejos para una reunión de trabajo de evaluación de desempeño",
  "¿Cómo pedir perdón por algo que dije sin querer?",
  "¿Cómo superar el miedo a la desconexión total?",
  "Dame ideas para una cita de paseo en kayak",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia?",
  "Tips para ser más considerado con el medio ambiente socialmente",
  "¿Cómo saber si mi pareja valora mi lealtad?",
  "¿Qué hacer si mi amigo me usa como terapeuta gratuito?",
  "Consejos para una despedida de club de lectura juvenil",
  "¿Cómo expresar vulnerabilidad de forma segura?",
  "¿Cómo mantener la amistad después de una diferencia política fuerte?",
  "Dame ejemplos de mensajes de aliento para personas con TDAH",
  "¿Cómo lidiar con la presión de tener una pareja ideal?",
  "Tips para una cita de feria de ciencias",
  "¿Cómo reconocer una relación que me da paz?",
  "¿Qué hacer si mi jefe me acosa en el trabajo?",
  "Consejos para una fiesta de Halloween de fantasmas",
  "¿Cómo ser más diligente en responder mensajes?",
  "¿Cómo responder cuando alguien me dice que soy su persona favorita?",
  "Dame frases para celebrar un nuevo comienzo",
  "¿Cómo manejar la presión de una boda perfecta?",
  "Tips para una conversación sobre cambio de ciudad con mi pareja",
  "¿Cómo saber si mi amistad es para toda la vida?",
  "¿Qué hacer si mi familia no acepta mis amigos?",
  "Consejos para una reunión de trabajo de planificación anual",
  "¿Cómo pedir que respeten mi identidad de género?",
  "¿Cómo superar el miedo a la apertura en público?",
  "Dame ideas para una cita de paseo en helicóptero",
  "¿Cómo actuar cuando alguien está teniendo un momento de tristeza repentina?",
  "Tips para ser más solidario en mi comunidad",
  "¿Cómo reconocer una relación donde puedo ser yo mismo?",
  "¿Qué hacer si mi pareja me manipula con sus emociones?",
  "Consejos para una despedida de club de ajedrez",
  "¿Cómo expresar alegría por el éxito de un rival?",
  "¿Cómo mantener la amistad después of una discusión de dinero?",
  "Dame ejemplos de mensajes de apoyo para personas con autismo",
  "¿Cómo lidiar con la envidia de mi propio hermano?",
  "Tips para una cita de observación de auroras boreales",
  "¿Cómo saber si mi pareja está comprometida emocionalmente?",
  "¿Qué hacer si mi amigo me cuenta que tiene pensamientos suicidas?",
  "Consejos para una fiesta de Halloween de brujas",
  "¿Cómo ser más compasivo con personas en situación de calle?",
  "¿Cómo responder cuando alguien me dice que le da miedo perderme?",
  "Dame frases para reconfortar a alguien con problemas de adicción",
  "¿Cómo manejar la presión de ser el perfecto anfitrión?",
  "Tips para una videollamada de trabajo nocturna",
  "¿Cómo reconocer una conversación que me energiza?",
  "¿Qué hacer si mi familia me hace sentir culpable por mis elecciones?",
  "Consejos para una reunión de trabajo de análisis de mercado",
  "¿Cómo pedir ayuda para mejorar mis habilidades sociales?",
  "¿Cómo superar el miedo a la soledad en una relación?",
  "Dame ideas para una cita de paseo en globo aerostático",
  "¿Cómo actuar cuando alguien está teniendo un ataque de ansiedad?",
  "Tips para ser más respetuoso con las diferencias de opinión",
  "¿Cómo saber si mi amistad es saludable a largo plazo?",
  "¿Qué hacer si mi pareja no me quiere presentar a su familia?",
  "Consejos para una despedida de club de natación",
  "¿Cómo expresar cariño a personas que no son demostrativas?",
  "¿Cómo mantener la amistad después de una competencia profesional?",
  "Dame ejemplos de mensajes de aliento para personas con fibromialgia",
  "¿Cómo lidiar con la presión de tener una vida social extensa?",
  "Tips para una cita de museo de historia natural",
  "¿Cómo reconocer una relación donde me siento valorado?",
  "¿Qué hacer si mi jefe me pide que interfiera en asuntos personales de compañeros?",
  "Consejos para una fiesta de Halloween de vampiros",
  "¿Cómo ser más proactivo en mantener relaciones familiares?",
  "¿Cómo responder cuando alguien me dice que soy su inspiración?",
  "Dame frases para celebrar un logro académico",
  "¿Cómo manejar la decepción cuando alguien no cumple una promesa?",
  "Tips para una conversación sobre salud sexual con mi pareja",
  "¿Cómo saber si mi amistad ha evolucionado a algo más?",
  "¿Qué hacer si mi familia me presiona para que vuelva a casa?",
  "Consejos para una reunión de trabajo de innovación",
  "¿Cómo pedir que me traten con dignidad?",
  "¿Cómo superar el miedo a la soledad después de una pérdida?",
  "Dame ideas para una cita de paseo en tren",
  "¿Cómo actuar cuando alguien está teniendo un momento de ira incontrolable?",
  "Tips para ser más amable con extraños",
  "¿Cómo reconocer una relación donde puedo crecer?",
  "¿Qué hacer si mi pareja no me apoya en momentos difíciles?",
  "Consejos para una despedida de club de montañismo",
  "¿Cómo expresar orgullo por un estudiante?",
  "¿Cómo mantener la amistad después de una traición menor?",
  "Dame ejemplos de mensajes de apoyo para personas con esquizofrenia",
  "¿Cómo lidiar con la presión de tener una carrera perfecta?",
  "Tips para una cita de feria de tecnología",
  "¿Cómo saber si mi pareja valora mi autenticidad?",
  "¿Qué hacer si mi amigo me acusa de cosas que no hice?",
  "Consejos para una fiesta de Halloween de zombis",
  "¿Cómo ser más tolerante con los errores de mi pareja?",
  "¿Cómo responder cuando alguien me dice que no me entiende?",
  "Dame frases para reconfortar a alguien con problemas de vivienda",
  "¿Cómo manejar la presión de tener un cuerpo perfecto para las redes?",
  "Tips para una videollamada de trabajo de fin de semana",
  "¿Cómo reconocer una conversación que me hace reflexionar?",
  "¿Qué hacer si mi familia no respeta mi orientación política?",
  "Consejos para una reunión de trabajo de diversidad e inclusión",
  "¿Cómo pedir una conversación seria sin asustar?",
  "¿Cómo superar el miedo a la exposición mediática?",
  "Dame ideas para una cita de paseo en moto",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia maníaca?",
  "Tips para ser más consciente de mis privilegios sociales",
  "¿Cómo saber si mi amistad es genuinamente desinteresada?",
  "¿Qué hacer si mi pareja me chantajea emocionalmente?",
  "Consejos para una despedida de club de fotografía aérea",
  "¿Cómo expresar preocupación por la salud de un ser querido?",
  "¿Cómo mantener la amistad después de una mudanza internacional?",
  "Dame ejemplos de mensajes de aliento para personas con dislexia",
  "¿Cómo lidiar con la presión de ser feliz todo el tiempo?",
  "Tips para una cita de observación de meteoros",
  "¿Cómo reconocer una relación que me da libertad?",
  "¿Qué hacer si mi jefe me hace sentir incompetente?",
  "Consejos para una fiesta de Halloween de hombres lobo",
  "¿Cómo ser más solidario con mis compañeros de trabajo?",
  "¿Cómo responder cuando alguien me dice que soy su refugio?",
  "Dame frases para celebrar un logro personal inesperado",
  "¿Cómo manejar la culpa de no estar con mi familia en fechas importantes?",
  "Tips para una conversación sobre espiritualidad con mi pareja",
  "¿Cómo saber si mi amistad me está alejando de mis metas?",
  "¿Qué hacer si mi familia me compara con mis primos?",
  "Consejos para una reunión de trabajo de sostenibilidad",
  "¿Cómo pedir ayuda para superar un trauma social?",
  "¿Cómo superar el miedo a la soledad en un país nuevo?",
  "Dame ideas para una cita de paseo en tranvía",
  "¿Cómo actuar cuando alguien está teniendo un momento de confusión extrema?",
  "Tips para ser más paciente con personas mayores",
  "¿Cómo reconocer una relación donde me siento escuchado?",
  "¿Qué hacer si mi pareja no quiere hablar de nuestro futuro?",
  "Consejos para una despedida de club de programación",
  "¿Cómo expresar admiración por un artista?",
  "¿Cómo mantener la amistad después de una ruptura amorosa compartida?",
  "Dame ejemplos de mensajes de apoyo para personas con epilepsia",
  "¿Cómo lidiar con la presión de tener una familia numerosa?",
  "Tips para una cita de feria de arte",
  "¿Cómo saber si mi pareja valora mi compañía?",
  "¿Qué hacer si mi amigo me hace sentir invisible?",
  "Consejos para una fiesta de Halloween de esqueletos",
  "¿Cómo ser más consciente del impacto de mis palabras?",
  "¿Cómo responder cuando alguien me dice que necesita distancia?",
  "Dame frases para reconfortar a alguien con problemas de empleo",
  "¿Cómo manejar la presión de tener una relación pública?",
  "Tips para una videollamada de trabajo de lunes por la mañana",
  "¿Cómo reconocer una conversación que me hace sentir comprendido?",
  "¿Qué hacer si mi familia no respeta mis creencias?",
  "Consejos para una reunión de trabajo de recursos humanos",
  "¿Cómo pedir que me den una oportunidad social?",
  "¿Cómo superar el miedo a la soledad en el silencio?",
  "Dame ideas para una cita de paseo en lancha",
  "¿Cómo actuar cuando alguien está teniendo un momento de pánico social?",
  "Tips para ser más empático con personas neurodivergentes",
  "¿Cómo saber si mi amistad es mutuamente beneficiosa?",
  "¿Qué hacer si mi pareja no me quiere escuchar?",
  "Consejos para una despedida de club de escritura",
  "¿Cómo expresar cariño a distancia de forma creativa?",
  "¿Cómo mantener la amistad después de un embarazo?",
  "Dame ejemplos de mensajes de aliento para personas con depresión postparto",
  "¿Cómo lidiar con la presión de tener una vida romántica como en las películas?",
  "Tips para una cita de observación de aves rapaces",
  "¿Cómo reconocer una relación que me da seguridad?",
  "¿Qué hacer si mi jefe me toma como su confidente personal?",
  "Consejos para una fiesta de Halloween de calaveras",
  "¿Cómo ser más respetuoso con las culturas ajenas?",
  "¿Cómo responder cuando alguien me dice que soy su hogar?",
  "Dame frases para celebrar un logro después de muchos intentos",
  "¿Cómo manejar la decepción cuando alguien no me valora?",
  "Tips para una conversación sobre límite territorial con mi pareja",
  "¿Cómo saber si mi amistad necesita más esfuerzo de mi parte?",
  "¿Qué hacer si mi familia me hace sentir avergonzado de mí mismo?",
  "Consejos para una reunión de trabajo de relaciones públicas",
  "¿Cómo pedir ayuda para entender mis propias emociones?",
  "¿Cómo superar el miedo a la soledad en una multitud?",
  "Dame ideas para una cita de paseo en teleférico",
  "¿Cómo actuar cuando alguien está teniendo un momento de vergüenza ajena?",
  "Tips para ser más considerado con personas con discapacidades invisibles",
  "¿Cómo reconocer una relación donde puedo descansar?",
  "¿Qué hacer si mi pareja no me quiere ver llorar?",
  "Consejos para una despedida de club de música",
  "¿Cómo expresar gratitud por la paciencia de alguien?",
  "¿Cómo mantener la amistad después de una gran discusión ideológica?",
  "Dame ejemplos de mensajes de apoyo para personas con trastorno bipolar",
  "¿Cómo lidiar con la presión de tener una vida social 24/7?",
  "Tips para una cita de feria de comida callejera",
  "¿Cómo saber si mi pareja valora mi crecimiento personal?",
  "¿Qué hacer si mi amigo me pide que mienta por él?",
  "Consejos para una fiesta de Halloween de payasos",
  "¿Cómo ser más atento a las señales no verbales?",
  "¿Cómo responder cuando alguien me dice que soy su persona de confianza?",
  "Dame frases para reconfortar a alguien con problemas de salud mental",
  "¿Cómo manejar la presión de mantener una imagen de pareja perfecta?",
  "Tips para una videollamada de trabajo de viernes por la tarde",
  "¿Cómo reconocer una conversación que me hace sentir vivo?",
  "¿Qué hacer si mi familia no respeta mi tiempo a solas?",
  "Consejos para una reunión de trabajo de finanzas",
  "¿Cómo pedir una reunión para aclarar malentendidos?",
  "¿Cómo superar el miedo a la soledad en una multitud?",
  "Dame ideas para una cita de paseo en caballo",
  "¿Cómo actuar cuando alguien está teniendo un momento de catarsis?",
  "Tips para ser más amable conmigo mismo socialmente",
  "¿Cómo saber si mi amistad es una prioridad para la otra persona?",
  "¿Qué hacer si mi pareja no me deja ser yo mismo?",
  "Consejos para una despedida de club de cine",
  "¿Cómo expresar preocupación por el bienestar de un amigo?",
  "¿Cómo mantener la amistad después de un diagnóstico médico?",
  "Dame ejemplos de mensajes de aliento para personas con artritis",
  "¿Cómo lidiar con la presión de tener una vida social Instagrammable?",
  "Tips para una cita de observación de flamencos",
  "¿Cómo reconocer una relación que me da alegría?",
  "¿Qué hacer si mi jefe me invita a eventos fuera del horario laboral?",
  "Consejos para una fiesta de Halloween de murciélagos",
  "¿Cómo ser más consciente de mi lenguaje corporal?",
  "¿Cómo responder cuando alguien me dice que soy su paz?",
  "Dame frases para celebrar un logro deportivo de equipo",
  "¿Cómo manejar la culpa de necesitar tiempo a solas?",
  "Tips para una conversación sobre cambio de trabajo con mi pareja",
  "¿Cómo saber si mi amistad me está ayudando a crecer?",
  "¿Qué hacer si mi familia me hace sentir que no pertenezco?",
  "Consejos para una reunión de trabajo de legal",
  "¿Cómo pedir que me expliquen algo sin sentirme tonto?",
  "¿Cómo superar el miedo a la soledad en el transporte público?",
  "Dame ideas para una cita de paseo en segway",
  "¿Cómo actuar cuando alguien está teniendo un momento de desconexión emocional?",
  "Tips para ser más comprensivo con personas con TEA",
  "¿Cómo reconocer una relación donde me siento aceptado?",
  "¿Qué hacer si mi pareja no me deja tener amigos?",
  "Consejos para una despedida de club de gastronomía",
  "¿Cómo expresar admiración por un mentor?",
  "¿Cómo mantener la amistad después de una gran distancia geográfica?",
  "Dame ejemplos de mensajes de apoyo para personas con ansiedad generalizada",
  "¿Cómo lidiar con la presión de tener una boda extravagante?",
  "Tips para una cita de feria de moda",
  "¿Cómo saber si mi pareja valora mi tiempo de calidad?",
  "¿Qué hacer si mi amigo me hace competencia todo el tiempo?",
  "Consejos para una fiesta de Halloween de fantasmas japoneses",
  "¿Cómo ser más respetuoso con los espacios seguros?",
  "¿Cómo responder cuando alguien me dice que soy su alegría?",
  "Dame frases para reconfortar a alguien con problemas de pareja reciente",
  "¿Cómo manejar la presión de tener una relación sin conflictos?",
  "Tips para una videollamada de trabajo de emergencia",
  "¿Cómo reconocer una conversación que me hace sentir esperanza?",
  "¿Qué hacer si mi familia no respeta mi necesidad de silencio?",
  "Consejos para una reunión de trabajo de operaciones",
  "¿Cómo pedir ayuda para manejar el estrés social?",
  "¿Cómo superar el miedo a la soledad en una habitación llena de gente?",
  "Dame ideas para una cita de paseo en scooter",
  "¿Cómo actuar cuando alguien está teniendo un momento de hipersensibilidad?",
  "Tips para ser más empático con personas con discapacidad visual",
  "¿Cómo saber si mi amistad es lo suficientemente fuerte?",
  "¿Qué hacer si mi pareja no me permite expresar tristeza?",
  "Consejos para una despedida de club de running",
  "¿Cómo expresar orgullo por un logro compartido?",
  "¿Cómo mantener la amistad después de un cambio de religión?",
  "Dame ejemplos de mensajes de aliento para personas con diabetes",
  "¿Cómo lidiar con la presión de tener una vida social perfectamente equilibrada?",
  "Tips para una cita de observación de bioluminiscencia",
  "¿Cómo reconocer una relación que me da paz mental?",
  "¿Qué hacer si mi jefe me pide que cubra ilegalidades?",
  "Consejos para una fiesta de Halloween de yokai",
  "¿Cómo ser más considerado con personas con discapacidad auditiva?",
  "¿Cómo responder cuando alguien me dice que soy su fortaleza?",
  "Dame frases para celebrar un logro creativo",
  "¿Cómo manejar la decepción cuando alguien no me entiende?",
  "Tips para una conversación sobre adopción de mascotas con mi pareja",
  "¿Cómo saber si mi amistad me está enseñando algo valioso?",
  "¿Qué hacer si mi familia me critica por mi estilo de vida?",
  "Consejos para una reunión de trabajo de ventas",
  "¿Cómo pedir una cita sin usar aplicaciones?",
  "¿Cómo superar el miedo a la soledad en un avión?",
  "Dame ideas para una cita de paseo en patines",
  "¿Cómo actuar cuando alguien está teniendo un momento de paranoia leve?",
  "Tips para ser más inclusivo en conversaciones grupales",
  "¿Cómo reconocer una relación donde me siento amado?",
  "¿Qué hacer si mi pareja no me permite tener hobbies solitarios?",
  "Consejos para una despedida de club de yoga",
  "¿Cómo expresar gratitud por un gesto inesperado?",
  "¿Cómo mantener la amistad después de una gran diferencia de estatus económico?",
  "Dame ejemplos de mensajes de apoyo para personas con VIH",
  "¿Cómo lidiar con la presión de tener una vida social sin límites de edad?",
  "Tips para una cita de feria de ciencia ficción",
  "¿Cómo saber si mi pareja valora mi inteligencia emocional?",
  "¿Qué hacer si mi amigo me pide que finja ser otra persona?",
  "Consejos para una fiesta de Halloween de demonios",
  "¿Cómo ser más consciente de los microagresiones?",
  "¿Cómo responder cuando alguien me dice que soy su inspiración diaria?",
  "Dame frases para reconfortar a alguien con problemas familiares",
  "¿Cómo manejar la presión de tener una relación sin secretos?",
  "Tips para una videollamada de trabajo de capacitación",
  "¿Cómo reconocer una conversación que me hace sentir pertenencia?",
  "¿Qué hacer si mi familia no respeta mi orientación sexual?",
  "Consejos para una reunión de trabajo de marketing",
  "¿Cómo pedir ayuda para superar la timidez extrema?",
  "¿Cómo superar el miedo a la soledad en un hospital?",
  "Dame ideas para una cita de paseo en burro",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia creativa?",
  "Tips para ser más respetuoso con los tiempos ajenos",
  "¿Cómo saber si mi amistad es una fuente de felicidad?",
  "¿Qué hacer si mi pareja no me deja expresar enfado?",
  "Consejos para una despedida de club de ajedrez rápido",
  "¿Cómo expresar alegría por un nacimiento?",
  "¿Cómo mantener la amistad después de una denuncia pública?",
  "Dame ejemplos de mensajes de aliento para personas con cáncer",
  "¿Cómo lidiar con la presión de tener una vida social ecológicamente perfecta?",
  "Tips para una cita de observación de tiburones",
  "¿Cómo reconocer una relación que me da estabilidad?",
  "¿Qué hacer si mi jefe me acosa sexualmente?",
  "Consejos para una fiesta de Halloween de monstruos clásicos",
  "¿Cómo ser más empático con personas que sufren discriminación?",
  "¿Cómo responder cuando alguien me dice que soy su refugio emocional?",
  "Dame frases para celebrar un logro después de superar una adversidad",
  "¿Cómo manejar la culpa de poner límites con mi familia?",
  "Tips para una conversación sobre mudanza internacional con mi pareja",
  "¿Cómo saber si mi amistad me está animando a ser mejor?",
  "¿Qué hacer si mi familia me hace sentir culpable por mis límites?",
  "Consejos para una reunión de trabajo de logística",
  "¿Cómo pedir ayuda para manejar relaciones difíciles?",
  "¿Cómo superar el miedo a la soledad en una residencia de ancianos?",
  "Dame ideas para una cita de paseo en canoa",
  "¿Cómo actuar cuando alguien está teniendo un momento de nostalgia intensa?",
  "Tips para ser más considerado con personas con alergias alimentarias",
  "¿Cómo reconocer una relación donde me siento completo?",
  "¿Qué hacer si mi pareja no me quiere compartir sus emociones?",
  "Consejos para una despedida de club de pintura",
  "¿Cómo expresar admiración por un colega sin competir?",
  "¿Cómo mantener la amistad después de una gran victoria personal?",
  "Dame ejemplos de mensajes de apoyo para personas con ELA",
  "¿Cómo lidiar con la presión de tener una vida social sin fronteras?",
  "Tips para una cita de feria de videojuegos",
  "¿Cómo saber si mi pareja valora mi lealtad incondicional?",
  "¿Qué hacer si mi amigo me pide que deje a mi pareja?",
  "Consejos para una fiesta de Halloween de robots",
  "¿Cómo ser más consciente de mi impacto emocional en otros?",
  "¿Cómo responder cuando alguien me dice que soy su paz mental?",
  "Dame frases para reconfortar a alguien con problemas de identidad",
  "¿Cómo manejar la presión de tener una relación de cuento de hadas?",
  "Tips para una videollamada de trabajo de revisión trimestral",
  "¿Cómo reconocer una conversación que me hace sentir en paz?",
  "¿Qué hacer si mi familia no respeta mi identidad de género?",
  "Consejos para una reunión de trabajo de desarrollo de producto",
  "¿Cómo pedir ayuda para mejorar mi autoestima social?",
  "¿Cómo superar el miedo a la soledad en una montaña rusa emocional?",
  "Dame ideas para una cita de paseo en bicicleta tandem",
  "¿Cómo actuar cuando alguien está teniendo un momento de claridad repentina?",
  "Tips para ser más solidario con personas en situación vulnerable",
  "¿Cómo saber si mi amistad es una inversión emocional positiva?",
  "¿Qué hacer si mi pareja no me permite tener secretos inocentes?",
  "Consejos para una despedida de club de astronomía",
  "¿Cómo expresar cariño a un amigo que no le gustan los abrazos?",
  "¿Cómo mantener la amistad después de una gran apuesta arriesgada?",
  "Dame ejemplos de mensajes de aliento para personas con lupus",
  "¿Cómo lidiar con la presión de tener una vida social que inspire a otros?",
  "Tips para una cita de observación de delfines",
  "¿Cómo reconocer una relación que me da libertad para ser quien soy?",
  "¿Qué hacer si mi jefe me pide que finja competencia que no tengo?",
  "Consejos para una fiesta de Halloween de extraterrestres",
  "¿Cómo ser más respetuoso con los pronombres de las personas?",
  "¿Cómo responder cuando alguien me dice que soy su lugar seguro?",
  "Dame frases para celebrar un logro después de mucho esfuerzo",
  "¿Cómo manejar la decepción cuando alguien me falla emocionalmente?",
  "Tips para una conversación sobre jubilación anticipada con mi pareja",
  "¿Cómo saber si mi amistad es un reflejo de quien quiero ser?",
  "¿Qué hacer si mi familia me compara con versiones anteriores de mí mismo?",
  "Consejos para una reunión de trabajo de expansión internacional",
  "¿Cómo pedir ayuda para entender las dinámicas sociales?",
  "¿Cómo superar el miedo a la soledad en una relación a distancia?",
  "Dame ideas para una cita de paseo en hoverboard",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia espiritual?",
  "Tips para ser más empático con personas con trastorno de la personalidad",
  "¿Cómo reconocer una relación donde me siento respetado?",
  "¿Qué hacer si mi pareja no me permite tener amigos del sexo opuesto?",
  "Consejos para una despedida de club de jardinería",
  "¿Cómo expresar gratitud por una segunda oportunidad?",
  "¿Cómo mantener la amistad después de un escándalo público?",
  "Dame ejemplos de mensajes de apoyo para personas con distrofia muscular",
  "¿Cómo lidiar con la presión de tener una vida social innovadora?",
  "Tips para una cita de feria de comida vegana",
  "¿Cómo saber si mi pareja valora mi comprensión?",
  "¿Qué hacer si mi amigo me pide que elija entre él y mi pareja?",
  "Consejos para una fiesta de Halloween de piratas",
  "¿Cómo ser más consciente de mis sesgos sociales?",
  "¿Cómo responder cuando alguien me dice que soy su esperanza?",
  "Dame frases para reconfortar a alguien con problemas de autoestima",
  "¿Cómo manejar la presión de tener una relación sin celos?",
  "Tips para una videollamada de trabajo de presentación a inversores",
  "¿Cómo reconocer una conversación que me hace sentir valioso?",
  "¿Qué hacer si mi familia no respeta mi autonomía económica?",
  "Consejos para una reunión de trabajo de cumplimiento normativo",
  "¿Cómo pedir ayuda para superar el miedo al rechazo social?",
  "¿Cómo superar el miedo a la soledad en un nuevo trabajo?",
  "Dame ideas para una cita de paseo en rikscha",
  "¿Cómo actuar cuando alguien está teniendo un momento de depresión leve?",
  "Tips para ser más amable con personas que están aprendiendo",
  "¿Cómo saber si mi amistad me está motivando a alcanzar mis sueños?",
  "¿Qué hacer si mi pareja no me permite llorar?",
  "Consejos para una despedida de club de robótica",
  "¿Cómo expresar orgullo por un estudiante con dificultades?",
  "¿Cómo mantener la amistad después de una diferencia ética fundamental?",
  "Dame ejemplos de mensajes de aliento para personas con esclerosis múltiple",
  "¿Cómo lidiar con la presión de tener una vida social sin prejuicios?",
  "Tips para una cita de observación de ballenas jorobadas",
  "¿Cómo reconocer una relación que me da confianza en mí mismo?",
  "¿Qué hacer si mi jefe me pide que trabaje en mi día de descanso?",
  "Consejos para una fiesta de Halloween de ninjas",
  "¿Cómo ser más empático con personas que han sufrido abuso?",
  "¿Cómo responder cuando alguien me dice que soy su luz?",
  "Dame frases para celebrar un logro científico",
  "¿Cómo manejar la culpa de no poder complacer a todos?",
  "Tips para una conversación sobre salud financiera con mi pareja",
  "¿Cómo saber si mi amistad es un espacio seguro?",
  "¿Qué hacer si mi familia me hace sentir que debo algo por ellos?",
  "Consejos para una reunión de trabajo de transformación digital",
  "¿Cómo pedir ayuda para manejar la ansiedad social?",
  "¿Cómo superar el miedo a la soledad en el matrimonio?",
  "Dame ideas para una cita de paseo en camello",
  "¿Cómo actuar cuando alguien está teniendo un momento de confusión identitaria?",
  "Tips para ser más considerado con personas con fobias sociales",
  "¿Cómo reconocer una relación donde me siento valorado por lo que soy?",
  "¿Qué hacer si mi pareja no me permite tener amigos en común?",
  "Consejos para una despedida de club de cocina internacional",
  "¿Cómo expresar admiración por un rival deportivo?",
  "¿Cómo mantener la amistad después de una gran pérdida económica compartida?",
  "Dame ejemplos de mensajes de apoyo para personas con distrofia de Duchenne",
  "¿Cómo lidiar con la presión de tener una vida social perfectamente organizada?",
  "Tips para una cita de feria de cerveza artesanal",
  "¿Cómo saber si mi pareja valora mi apoyo incondicional?",
  "¿Qué hacer si mi amigo me pide que le cuente secretos de otros?",
  "Consejos para una fiesta de Halloween de superhéroes",
  "¿Cómo ser más consciente de mi consumo emocional ajeno?",
  "¿Cómo responder cuando alguien me dice que soy su razón de sonreír?",
  "Dame frases para reconfortar a alguien con problemas de adicción reciente",
  "¿Cómo manejar la presión de tener una relación sin mentiras blancas?",
  "Tips para una videollamada de trabajo de onboarding remoto",
  "¿Cómo reconocer una conversación que me hace sentir entendido?",
  "¿Qué hacer si mi familia no respeta mi necesidad de independencia?",
  "Consejos para una reunión de trabajo de fusiones y adquisiciones",
  "¿Cómo pedir ayuda para superar el aislamiento social?",
  "¿Cómo superar el miedo a la soledad en la vejez temprana?",
  "Dame ideas para una cita de paseo en monociclo",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia romántica?",
  "Tips para ser más respetuoso con las experiencias traumáticas ajenas",
  "¿Cómo saber si mi amistad es genuinamente compasiva?",
  "¿Qué hacer si mi pareja no me permite tener amigos de la infancia?",
  "Consejos para una despedida de club de senderismo nocturno",
  "¿Cómo expresar gratitud por un amigo que siempre está ahí?",
  "¿Cómo mantener la amistad después de una gran diferencia generacional?",
  "Dame ejemplos de mensajes de aliento para personas con insuficiencia renal",
  "¿Cómo lidiar con la presión de tener una vida social sin límites de tiempo?",
  "Tips para una cita de observación de perezosos",
  "¿Cómo reconocer una relación que me da seguridad emocional?",
  "¿Qué hacer si mi jefe me amenaza con despedirme sin causa?",
  "Consejos para una fiesta de Halloween de magos",
  "¿Cómo ser más consciente de mi lenguaje no verbal?",
  "¿Cómo responder cuando alguien me dice que soy su confidente favorito?",
  "Dame frases para celebrar un logro educativo",
  "¿Cómo manejar la decepción cuando alguien no está disponible emocionalmente?",
  "Tips para una conversación sobre crianza con mi pareja",
  "¿Cómo saber si mi amistad me está ayudando a sanar?",
  "¿Qué hacer si mi familia me compara con mis amigos?",
  "Consejos para una reunión de trabajo de investigación y desarrollo",
  "¿Cómo pedir ayuda para entender la dinámica de mi familia?",
  "¿Cómo superar el miedo a la soledad después de un divorcio?",
  "Dame ideas para una cita de paseo en barco de vapor",
  "¿Cómo actuar cuando alguien está teniendo un momento de desilusión amorosa?",
  "Tips para ser más empático con personas con trastorno obsesivo compulsivo",
  "¿Cómo reconocer una relación donde me siento protegido?",
  "¿Qué hacer si mi pareja no me permite tener intereses propios?",
  "Consejos para una despedida de club de natación sincronizada",
  "¿Cómo expresar alegría por un logro académico de un amigo?",
  "¿Cómo mantener la amistad después de una gran apuesta financiera?",
  "Dame ejemplos de mensajes de apoyo para personas con hepatitis",
  "¿Cómo lidiar con la presión de tener una vida social sin fronteras geográficas?",
  "Tips para una cita de feria de diseño",
  "¿Cómo saber si mi pareja valora mi capacidad de escuchar?",
  "¿Qué hacer si mi amigo me pide que mienta a su pareja?",
  "Consejos para una fiesta de Halloween de detectives",
  "¿Cómo ser más consciente de la carga emocional que dejo en otros?",
  "¿Cómo responder cuando alguien me dice que soy su persona favorita del mundo?",
  "Dame frases para reconfortar a alguien con problemas de aprendizaje",
  "¿Cómo manejar la presión de tener una relación sin inseguridades?",
  "Tips para una videollamada de trabajo de presentación de resultados",
  "¿Cómo reconocer una conversación que me hace sentir esperanzado?",
  "¿Qué hacer si mi familia no respeta mi derecho a la privacidad digital?",
  "Consejos para una reunión de trabajo de recursos humanos digitales",
  "¿Cómo pedir ayuda para superar el miedo a hablar en público?",
  "¿Cómo superar el miedo a la soledad en un entorno laboral tóxico?",
  "Dame ideas para una cita de paseo en tren turístico",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia intelectual?",
  "Tips para ser más considerado con personas con sensibilidad química múltiple",
  "¿Cómo saber si mi amistad es una fuente de inspiración constante?",
  "¿Qué hacer si mi pareja no me permite tener amigos virtuales?",
  "Consejos para una despedida de club de pádel",
  "¿Cómo expresar cariño a un ser querido con demencia?",
  "¿Cómo mantener la amistad después de una gran pérdida deportiva?",
  "Dame ejemplos de mensajes de aliento para personas con fibrosis quística",
  "¿Cómo lidiar con la presión de tener una vida social sin discriminación?",
  "Tips para una cita de observación de pinguinos",
  "¿Cómo reconocer una relación que me da paz en el caos?",
  "¿Qué hacer si mi jefe me pide que haga trabajo no ético?",
  "Consejos para una fiesta de Halloween de samuráis",
  "¿Cómo ser más empático con personas con trastorno de estrés postraumático?",
  "¿Cómo responder cuando alguien me dice que soy su calmante?",
  "Dame frases para celebrar un logro después de muchas caídas",
  "¿Cómo manejar la culpa de no poder estar en todos lados?",
  "Tips para una conversación sobre salud mental con mi pareja",
  "¿Cómo saber si mi amistad me está empujando fuera de mi zona de confort positivamente?",
  "¿Qué hacer si mi familia me hace sentir que nunca soy suficiente?",
  "Consejos para una reunión de trabajo de análisis de competidores",
  "¿Cómo pedir ayuda para manejar la presión de grupo?",
  "¿Cómo superar el miedo a la soledad en una ciudad grande?",
  "Dame ideas para una cita de paseo en funicular",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia artística?",
  "Tips para ser más respetuoso con las identidades culturales ajenas",
  "¿Cómo reconocer una relación donde me siento apreciado?",
  "¿Qué hacer si mi pareja no me permite tener hobbies con otras personas?",
  "Consejos para una despedida de club de equitación",
  "¿Cómo expresar preocupación por la seguridad de un amigo?",
  "¿Cómo mantener la amistad después de un gran cambio de imagen?",
  "Dame ejemplos de mensajes de apoyo para personas con enfermedad de Crohn",
  "¿Cómo lidiar con la presión de tener una vida social sin prejuicios de género?",
  "Tips para una cita de feria de anime",
  "¿Cómo saber si mi pareja valora mi dedicación?",
  "¿Qué hacer si mi amigo me acusa de ser falso?",
  "Consejos para una fiesta de Halloween de cowboys",
  "¿Cómo ser más consciente de mi presencia emocional en espacios grupales?",
  "¿Cómo responder cuando alguien me dice que soy su bálsamo?",
  "Dame frases para reconfortar a alguien con problemas de memoria",
  "¿Cómo manejar la presión de tener una relación sin manipulación?",
  "Tips para una videollamada de trabajo de contratación",
  "¿Cómo reconocer una conversación que me hace sentir reconfortado?",
  "¿Qué hacer si mi familia no respeta mi derecho a votar diferente?",
  "Consejos para una reunión de trabajo de análisis de datos",
  "¿Cómo pedir ayuda para superar el trauma de una ruptura?",
  "¿Cómo superar el miedo a la soledad en un mundo hiperconectado?",
  "Dame ideas para una cita de paseo en teleférico de montaña",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia musical?",
  "Tips para ser más empático con personas con trastorno límite de la personalidad",
  "¿Cómo saber si mi amistad es una relación de igual a igual?",
  "¿Qué hacer si mi pareja no me permite tener secretos personales inocentes?",
  "Consejos para una despedida de club de golf",
  "¿Cómo expresar gratitud por un profesor que cambió mi vida?",
  "¿Cómo mantener la amistad después de una gran mudanza internacional?",
  "Dame ejemplos de mensajes de aliento para personas con talasemia",
  "¿Cómo lidiar con la presión de tener una vida social sin límites de clase?",
  "Tips para una cita de observación de nutrias marinas",
  "¿Cómo reconocer una relación que me da confianza en el futuro?",
  "¿Qué hacer si mi jefe me pide que cubra sus errores?",
  "Consejos para una fiesta de Halloween de gladiadores",
  "¿Cómo ser más respetuoso con las experiencias de inmigrantes?",
  "¿Cómo responder cuando alguien me dice que soy su refugio del mundo?",
  "Dame frases para celebrar un logro deportivo individual",
  "¿Cómo manejar la decepción cuando alguien no me apoya en público?",
  "Tips para una conversación sobre jubilación con mis padres",
  "¿Cómo saber si mi amistad me está enseñando a ser más resiliente?",
  "¿Qué hacer si mi familia me compara con versiones ideales de mí mismo?",
  "Consejos para una reunión de trabajo de customer success",
  "¿Cómo pedir ayuda para entender las señales sociales?",
  "¿Cómo superar el miedo a la soledad en una relación de conveniencia?",
  "Dame ideas para una cita de paseo en aerodeslizador",
  "¿Cómo actuar cuando alguien está teniendo un momento de claridad emocional?",
  "Tips para ser más considerado con personas con trastornos alimentarios",
  "¿Cómo reconocer una relación donde me siento libre de juicios?",
  "¿Qué hacer si mi pareja no me permite tener amigos que no le gustan?",
  "Consejos para una despedida de club de pilates",
  "¿Cómo expresar admiración por un voluntario?",
  "¿Cómo mantener la amistad después de una gran diferencia de opinión política?",
  "Dame ejemplos de mensajes de apoyo para personas con anemia falciforme",
  "¿Cómo lidiar con la presión de tener una vida social sin fronteras religiosas?",
  "Tips para una cita de feria de chocolate",
  "¿Cómo saber si mi pareja valora mi honestidad radical?",
  "¿Qué hacer si mi amigo me pide que finja que no pasó nada?",
  "Consejos para una fiesta de Halloween de caballeros",
  "¿Cómo ser más consciente de mi influencia en los demás?",
  "¿Cómo responder cuando alguien me dice que soy su calma?",
  "Dame frases para reconfortar a alguien con problemas de sueño",
  "¿Cómo manejar la presión de tener una relación sin celos irracionales?",
  "Tips para una videollamada de trabajo de presentación a cliente",
  "¿Cómo reconocer una conversación que me hace sentir revitalizado?",
  "¿Qué hacer si mi familia no respeta mi autonomía para tomar decisiones médicas?",
  "Consejos para una reunión de trabajo de gestión de proyectos",
  "¿Cómo pedir ayuda para mejorar mis habilidades de comunicación no violenta?",
  "¿Cómo superar el miedo a la soledad en una relación abierta?",
  "Dame ideas para una cita de paseo en carruaje",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia deportiva?",
  "Tips para ser más empático con personas con trastorno de déficit de atención",
  "¿Cómo saber si mi amistad es un refugio genuino?",
  "¿Qué hacer si mi pareja no me permite tener amigos cercanos?",
  "Consejos para una despedida de club de tenis",
  "¿Cómo expresar orgullo por un hijo que superó una dificultad?",
  "¿Cómo mantener la amistad después de una gran victoria competitiva?",
  "Dame ejemplos de mensajes de aliento para personas con hemofilia",
  "¿Cómo lidiar con la presión de tener una vida social sin prejuicios raciales?",
  "Tips para una cita de observación de koalas",
  "¿Cómo reconocer una relación que me da estabilidad emocional?",
  "¿Qué hacer si mi jefe me acusa públicamente de errores que no cometí?",
  "Consejos para una fiesta de Halloween de vaqueros del espacio",
  "¿Cómo ser más consciente de la energía que traigo a las interacciones?",
  "¿Cómo responder cuando alguien me dice que soy su paz en el caos?",
  "Dame frases para celebrar un logro después de superar un miedo",
  "¿Cómo manejar la culpa de no poder estar presente para todos?",
  "Tips para una conversación sobre salud física con mi pareja",
  "¿Cómo saber si mi amistad me está animando a ser auténtico?",
  "¿Qué hacer si mi familia me hace sentir que debo renunciar a mis sueños?",
  "Consejos para una reunión de trabajo de inteligencia artificial",
  "¿Cómo pedir ayuda para manejar el duelo?",
  "¿Cómo superar el miedo a la soledad en una relación sin amor?",
  "Dame ideas para una cita de paseo en góndola",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia científica?",
  "Tips para ser más respetuoso con las identidades de género no binarias",
  "¿Cómo reconocer una relación donde me siento aceptado incondicionalmente?",
  "¿Qué hacer si mi pareja no me permite tener amigos de trabajo?",
  "Consejos para una despedida de club de surf",
  "¿Cómo expresar gratitud por un vecino solidario?",
  "¿Cómo mantener la amistad después de una gran pérdida personal compartida?",
  "Dame ejemplos de mensajes de apoyo para personas con marfan syndrome",
  "¿Cómo lidiar con la presión de tener una vida social sin fronteras lingüísticas?",
  "Tips para una cita de feria de quesos",
  "¿Cómo saber si mi pareja valora mi sentido del humor?",
  "¿Qué hacer si mi amigo me pide que elija entre mi familia y él?",
  "Consejos para una fiesta de Halloween de piratas del caribe",
  "¿Cómo ser más consciente de los privilegios que tengo en mis interacciones?",
  "¿Cómo responder cuando alguien me dice que soy su refugio de paz?",
  "Dame frases para reconfortar a alguien con problemas de concentración",
  "¿Cómo manejar la presión de tener una relación sin peleas?",
  "Tips para una videollamada de trabajo de alianzas estratégicas",
  "¿Cómo reconocer una conversación que me hace sentir pleno?",
  "¿Qué hacer si mi familia no respeta mi derecho a la educación que elijo?",
  "Consejos para una reunión de trabajo de transformación cultural",
  "¿Cómo pedir ayuda para superar el miedo a la intimidad física?",
  "¿Cómo superar el miedo a la soledad en una relación codependiente?",
  "Dame ideas para una cita de paseo en velero",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia tecnológica?",
  "Tips para ser más considerado con personas con sensibilidad al ruido",
  "¿Cómo saber si mi amistad es un espacio de crecimiento mutuo?",
  "¿Qué hacer si mi pareja no me permite tener amigos de la universidad?",
  "Consejos para una despedida de club de escalada",
  "¿Cómo expresar admiración por un artista callejero?",
  "¿Cómo mantener la amistad después de una gran diferencia de estilo de vida?",
  "Dame ejemplos de mensajes de aliento para personas con osteogénesis imperfecta",
  "¿Cómo lidiar con la presión de tener una vida social perfectamente diversa?",
  "Tips para una cita de observación de focas",
  "¿Cómo reconocer una relación que me da confianza para soñar?",
  "¿Qué hacer si mi jefe me pide que firme documentos sin leer?",
  "Consejos para una fiesta de Halloween de steampunk",
  "¿Cómo ser más empático con personas con trastorno de ansiedad social?",
  "¿Cómo responder cuando alguien me dice que soy su refugio de alegría?",
  "Dame frases para celebrar un logro después de superar una enfermedad",
  "¿Cómo manejar la decepción cuando alguien no me celebra?",
  "Tips para una conversación sobre cambio de estilo de vida con mi pareja",
  "¿Cómo saber si mi amistad me está ayudando a superar mis miedos?",
  "¿Qué hacer si mi familia me compara con mis compañeros de trabajo?",
  "Consejos para una reunión de trabajo de experiencia del cliente",
  "¿Cómo pedir ayuda para entender mi orientación sexual?",
  "¿Cómo superar el miedo a la soledad en una residencia estudiantil?",
  "Dame ideas para una cita de paseo en tractor",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia culinaria?",
  "Tips para ser más empático con personas con trastorno de la conducta alimentaria",
  "¿Cómo reconocer una relación donde me siento querido por mis defectos?",
  "¿Qué hacer si mi pareja no me permite tener amigos en redes sociales?",
  "Consejos para una despedida de club de ciclismo",
  "¿Cómo expresar preocupación por el medio ambiente sin sonar alarmista?",
  "¿Cómo mantener la amistad después de una gran diferencia de principios morales?",
  "Dame ejemplos de mensajes de apoyo para personas con síndrome de Down",
  "¿Cómo lidiar con la presión de tener una vida social sin prejuicios de edad?",
  "Tips para una cita de feria de artesanías",
  "¿Cómo saber si mi pareja valora mi paciencia?",
  "¿Qué hacer si mi amigo me pide que le dé dinero para una adicción?",
  "Consejos para una fiesta de Halloween de espías",
  "¿Cómo ser más consciente de las expectativas que pongo en otros?",
  "¿Cómo responder cuando alguien me dice que soy su luz en la oscuridad?",
  "Dame frases para reconfortar a alguien con problemas de visión",
  "¿Cómo manejar la presión de tener una relación sin drama?",
  "Tips para una videollamada de trabajo de presentación de producto",
  "¿Cómo reconocer una conversación que me hace sentir motivado?",
  "¿Qué hacer si mi familia no respeta mi derecho a elegir mi propia familia?",
  "Consejos para una reunión de trabajo de innovación abierta",
  "¿Cómo pedir ayuda para superar el miedo a la autoridad?",
  "¿Cómo superar el miedo a la soledad en un hospital psiquiátrico?",
  "Dame ideas para una cita de paseo en moto acuática",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia literaria?",
  "Tips para ser más respetuoso con las experiencias de personas sin hogar",
  "¿Cómo saber si mi amistad es una relación de confianza absoluta?",
  "¿Qué hacer si mi pareja no me permite tener amigos que sean ex?",
  "Consejos para una despedida de club de bádminton",
  "¿Cómo expresar orgullo por un familiar que superó una adicción?",
  "¿Cómo mantener la amistad después de una gran diferencia de niveles educativos?",
  "Dame ejemplos de mensajes de aliento para personas con síndrome de Tourette",
  "¿Cómo lidiar con la presión de tener una vida social sin fronteras económicas?",
  "Tips para una cita de observación de jirafas",
  "¿Cómo reconocer una relación que me da paz en medio de la tormenta?",
  "¿Qué hacer si mi jefe me pide que finja enfermedad?",
  "Consejos para una fiesta de Halloween de vaqueros zombies",
  "¿Cómo ser más consciente de mis palabras cuando estoy enojado?",
  "¿Cómo responder cuando alguien me dice que soy su paz interior?",
  "Dame frases para celebrar un logro después de mucho sacrificio",
  "¿Cómo manejar la culpa de alejarme de personas tóxicas?",
  "Tips para una conversación sobre religión con mi pareja",
  "¿Cómo saber si mi amistad me está enseñando a perdonar?",
  "¿Qué hacer si mi familia me hace sentir que no merezco amor?",
  "Consejos para una reunión de trabajo de análisis financiero",
  "¿Cómo pedir ayuda para superar la codependencia?",
  "¿Cómo superar el miedo a la soledad en un centro de rehabilitación?",
  "Dame ideas para una cita de paseo en patineta",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia política?",
  "Tips para ser más considerado con personas con trastorno del espectro autista",
  "¿Cómo reconocer una relación donde me siento en casa?",
  "¿Qué hacer si mi pareja no me permite tener amigos que no conoce?",
  "Consejos para una despedida de club de esgrima",
  "¿Cómo expresar gratitud por un médico que me ayudó mucho?",
  "¿Cómo mantener la amistad después de una gran apuesta emocional?",
  "Dame ejemplos de mensajes de apoyo para personas con síndrome de Rett",
  "¿Cómo lidiar con la presión de tener una vida social sin fronteras de género?",
  "Tips para una cita de feria de comida asiática",
  "¿Cómo saber si mi pareja valora mi compromiso?",
  "¿Qué hacer si mi amigo me pide que oculte evidencia de un delito?",
  "Consejos para una fiesta de Halloween de científicos locos",
  "¿Cómo ser más consciente de mis reacciones emocionales automáticas?",
  "¿Cómo responder cuando alguien me dice que soy su refugio de tranquilidad?",
  "Dame frases para reconfortar a alguien con problemas de audición",
  "¿Cómo manejar la presión de tener una relación sin dependencia emocional?",
  "Tips para una videollamada de trabajo de negociación",
  "¿Cómo reconocer una conversación que me hace sentir amado incondicionalmente?",
  "¿Qué hacer si mi familia no respeta mi derecho a la privacidad médica?",
  "Consejos para una reunión de trabajo de análisis de riesgos",
  "¿Cómo pedir ayuda para superar el miedo a la crítica?",
  "¿Cómo superar el miedo a la soledad en una relación sin comunicación?",
  "Dame ideas para una cita de paseo en scooter eléctrico",
  "¿Cómo actuar cuando alguien está teniendo un momento de euforia deportiva colectiva?",
  "Tips para ser más empático con personas con trastorno dismórfico corporal",
  "¿Cómo saber si mi amistad es una relación de apoyo incondicional?",
  "¿Qué hacer si mi pareja no me permite tener amigos del mismo género?",
  "Consejos para una despedida de club de voleibol",
  "¿Cómo expresar alegría por un logro científico de un amigo?",
  "¿Cómo mantener la amistad después de una gran diferencia de creencias científicas?",
  "Dame ejemplos de mensajes de aliento para personas con síndrome de Ehlers-Danlos",
  "¿Cómo lidiar con la presión de tener una vida social sin fronteras culturales?",
  "Tips para una cita de observación de elefantes",
  "¿Cómo reconocer una relación que me da seguridad para explorar?",
  "¿Qué hacer si mi jefe me pide que finja resultados?",
  "Consejos para una fiesta de Halloween de dinosaurios",
  "¿Cómo ser más respetuoso con las experiencias de personas con discapacidad física?",
  "¿Cómo responder cuando alguien me dice que soy su refugio de amor?",
  "Dame frases para celebrar un logro después de años de lucha",
  "¿Cómo manejar la decepción cuando alguien no me defiende?",
  "Tips para una conversación sobre salud emocional con mis hijos",
  "¿Cómo saber si mi amistad me está ayudando a encontrar mi voz?",
  "¿Qué hacer si mi familia me compara con mis compañeros de universidad?",
  "Consejos para una reunión de trabajo de responsabilidad social empresarial",
  "¿Cómo pedir ayuda para superar el aislamiento emocional?"
];

$totalQuestions = 1000;
$usersCount = 200;
$conversationsPerUser = 3;

$pdo->beginTransaction();

try {
    // Preparar statements
    $stmtUser = $pdo->prepare("INSERT INTO users (user_id) VALUES (:uid) ON DUPLICATE KEY UPDATE user_id=user_id");
    $stmtConv = $pdo->prepare("INSERT INTO conversations (conversation_id, user_id, title) VALUES (:cid, :uid, :title)");
    $stmtMsg  = $pdo->prepare("INSERT INTO messages (message_id, conversation_id, role, content, type) VALUES (:mid, :cid, 'user', :content, 'text')");

    $inserted = 0;
    $questionIndex = 0;

    for ($u = 1; $u <= $usersCount && $inserted < $totalQuestions; $u++) {
        $userId = 'user_seed_' . str_pad((string)$u, 4, '0', STR_PAD_LEFT);
        $stmtUser->execute([':uid' => $userId]);

        for ($c = 1; $c <= $conversationsPerUser && $inserted < $totalQuestions; $c++) {
            $convId = 'conv_seed_' . $userId . '_' . str_pad((string)$c, 3, '0', STR_PAD_LEFT);
            $title = 'Conversación ' . $c . ' - ' . mb_substr($questions[$questionIndex % count($questions)], 0, 40);
            $stmtConv->execute([':cid' => $convId, ':uid' => $userId, ':title' => $title]);

            $messagesPerConv = rand(1, 3);
            for ($m = 1; $m <= $messagesPerConv && $inserted < $totalQuestions; $m++) {
                $msgId = 'msg_seed_' . $convId . '_' . str_pad((string)$m, 3, '0', STR_PAD_LEFT);
                $content = $questions[$questionIndex % count($questions)];
                $stmtMsg->execute([':mid' => $msgId, ':cid' => $convId, ':content' => $content]);
                $inserted++;
                $questionIndex++;
            }
        }
    }

    $pdo->commit();
    echo "Se insertaron {$inserted} preguntas sociales en la base de datos.\n";
} catch (Throwable $e) {
    $pdo->rollBack();
    echo "Error: " . $e->getMessage() . "\n";
    exit(1);
}
